openapi: 3.1.0
info:
  version: 5.3.1-pre.0
  title: openapi-ipify
  description: OpenAPI client for ipify, a simple public IP address API
  license:
    name: MIT
    identifier: MIT
  contact:
    name: OpenAPI Clients Factory
    url: https://github.com/oapicf/openapi-ipify
    email: blah+oapicf@cliffano.com
servers:
  - url: https://api64.ipify.org
paths:
  /:
    get:
      summary: Get your public IP address
      operationId: getIp
      parameters:
        - name: format
          in: query
          description: Response format
          required: false
          schema:
            type: string
            enum:
              - json
              - jsonp
        - name: callback
          in: query
          description: JSONP callback function name
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Your public IP address
          content:
            text/plain:
              schema:
                type: string
              example: "192.168.1.1"
            application/json:
              schema:
                type: object
                properties:
                  ip:
                    type: string
                example:
                  ip: "192.168.1.1"
            application/javascript:
              schema:
                type: string
              example: "callback({\"ip\":\"192.168.1.1\"})"
