openapi: 3.0.0
info:
  version: 5.2.1-pre.0
  title: openapi-ipify
  description: OpenAPI client for ipify, a simple public IP address API
  license:
    name: MIT
  contact:
    name: Cliffano Subagio
    url: http://blog.cliffano.com
    email: blah@cliffano.com
servers:
  - url: https://api.ipify.org
paths:
  /:
    get:
      summary: Get your public IP address
      operationId: getIp
      parameters:
        - name: format
          in: query
          description: Response format
          required: false
          schema:
            type: string
            enum:
              - json
              - jsonp
        - name: callback
          in: query
          description: JSONP callback function name
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Your public IP address
          # This used to have multiple schemas based on
          # content type, but OAG only generates one
          # schema for all content types, so instead
          # of breaking the response parsing due to incompatible
          # schema, we opted to just using string as the schema.
          content:
            text/plain:
              schema:
                type: string
            application/javascript:
              schema:
                type: string
            application/json:
              schema:
                type: string
