openapi: 3.0.0
info:
  contact:
    email: blah+oapicf@cliffano.com
    name: OpenAPI Clients Factory
    url: https://github.com/oapicf/openapi-ipify
  description: "OpenAPI client for ipify, a simple public IP address API"
  license:
    name: MIT
  title: openapi-ipify
  version: 5.2.1-pre.0
servers:
- url: https://api.ipify.org
paths:
  /:
    get:
      operationId: getIp
      parameters:
      - description: Response format
        explode: true
        in: query
        name: format
        required: false
        schema:
          enum:
          - json
          - jsonp
          type: string
        style: form
      - description: JSONP callback function name
        explode: true
        in: query
        name: callback
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ip'
            application/javascript:
              schema:
                type: string
            text/plain:
              schema:
                type: string
          description: Your public IP address
      summary: Get your public IP address
components:
  schemas:
    Ip:
      example:
        ip: ip
      properties:
        ip:
          type: string
      required:
      - ip
