name: Publish API Documentation
'on':
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.OAPICF_GITHUB_TOKEN }}
          ref: main
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: make deps init-spec doc-latest doc-version
      - run: >-
          CACHE_DIR=/tmp gh-pages --dist doc/ --user "pakkunbot
          <blah+pakkun@cliffano.com>" --repo "https://cliffano:${{
          secrets.OAPICF_GITHUB_TOKEN
          }}@github.com/oapicf/openapi-okta-ip-ranges.git"
